spec:
  template:
    spec:
      containers:
      - name: jaeger-performance-wildfly-swarm-app
      - name: jaeger-agent
        image: "jaeger-agent:latest"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector.jaeger-infra.svc:14267"
        - "--processor.jaeger-binary.server-queue-size=300000"
